name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "hello world"
  build:
    needs:
      - foo
    strategy:
      matrix:
        bar:
          - environment: prod
            hello: world
          - environment: prod
            hello: bar
          - environment: dev
            hello: bar
          - environment: stage
            hello: bar
        exclude:
          - bar: {environment: prod}
          - bar: {environment: dev}
          - bar: {environment: stage}
          

    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.version }}
          echo ${{ matrix.environment }}
