name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "hello world"
  build:
    needs:
      - foo
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        version: [12, 14, 16]
        environment: [dev, prod, stage]
        exclude:
          - os: macos-latest
            version: 12
            environment: prod
          - os: windows-latest
            version: 16
          - os: ubuntu-latest
            version: 16
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.version }}
          echo ${{ matrix.environment }}
