name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  foo:
    runs-on: ubuntu-latest
    outputs:
      built_matrix: ${{ steps.foo.outputs.test }}
    steps:
      - name: Hello world
        id: foo
        run: |
          echo "hello world"
          echo "test=[{\"environment\": \"prod\"}]" >> $GITHUB_OUTPUT
  build:
    needs:
      - foo
    strategy:
      matrix:
        foo: ${{ fromJson(needs.foo.outputs.built_matrix) }}
          

#     environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo ${{ matrix.environment }}
          echo ${{ matrix.hello }}
