name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  foo:
    runs-on: ubuntu-latest
    outputs:
      built_matrix: ${{ steps.foo.outputs.test }}
    steps:
      - name: Hello world
        id: foo
        run: |
          TEST=$(cat <<-EOF
            [
              {
                "environment": "prod",
                "foo": "foo"
              },
              {
                "environment": "prod",
                "foo": "bar"
              },
              {
                "environment": "dev",
                "foo": "bar"
              },
              {
                "environment": "stage",
                "foo": "bar"
              }
            ]
          EOF
          )
          TEST=$(echo $TEST | jq -c '[.[] | select(.environment=="prod")] | tostring'
          echo "test=${TEST}" >> $GITHUB_OUTPUT
  build:
    needs:
      - foo
    strategy:
      matrix:
        foo: ${{ fromJson(needs.foo.outputs.built_matrix) }}
          

    environment: ${{ matrix.foo.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo ${{ matrix.foo.environment }}
          echo ${{ matrix.foo.foo }}
